# Generated by Django 2.1.2 on 2019-01-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='alert_1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='alert_2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='alert_3',
        ),
        migrations.RemoveField(
            model_name='member',
            name='alert_4',
        ),
        migrations.AddField(
            model_name='member',
            name='carer_alert',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Carer Alert'),
        ),
        migrations.AddField(
            model_name='member',
            name='financial_alert',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Financial Alert'),
        ),
        migrations.AddField(
            model_name='member',
            name='general_alert',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='General Alert'),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_alert',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Medical Alert'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='adult_investiture',
            field=models.DateField(blank=True, null=True, verbose_name='Adult Investiture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='alert_notes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alert notes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ambulance_fund',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ambulance Fund'),
        ),
        migrations.AlterField(
            model_name='member',
            name='app_form_issued',
            field=models.DateField(blank=True, null=True, verbose_name='App Form Issued'),
        ),
        migrations.AlterField(
            model_name='member',
            name='app_form_returned',
            field=models.DateField(blank=True, null=True, verbose_name='App Form Returned'),
        ),
        migrations.AlterField(
            model_name='member',
            name='app_sent_to_branch',
            field=models.DateField(blank=True, null=True, verbose_name='App Sent to Branch'),
        ),
        migrations.AlterField(
            model_name='member',
            name='appointment_review',
            field=models.DateField(blank=True, null=True, verbose_name='Appointment Review'),
        ),
        migrations.AlterField(
            model_name='member',
            name='blue_card_wwcc_first_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Blue Card/WWCC First Issued'),
        ),
        migrations.AlterField(
            model_name='member',
            name='blue_card_wwcc_next_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Blue Card/WWCC Next Expires'),
        ),
        migrations.AlterField(
            model_name='member',
            name='blue_card_wwcc_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Blue Card/WWCC Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_blue_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Carer 1 Blue card expiry'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_blue_card_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Blue Card #'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Carer 1 Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_employer',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Employer'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Fax'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_help_offer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carer 1 Help offer'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_interests',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Interests'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Mobile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_occupation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_previous_scouting',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Previous Scouting'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_relationship',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Relationship'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_skills',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carer 1 Skills'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_work_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 1 Work Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_blue_card_exp',
            field=models.DateField(blank=True, null=True, verbose_name='Carer 2 Blue Card Exp'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_blue_card_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Blue Card #'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Carer 2 Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_employer',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Employer'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Fax'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_help_offer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carer 2 Help offer'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_interests',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Interests'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Mobile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_occupation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_previous_scouting',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Previous Scouting'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_relationship',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Relationship'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_skills',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carer 2 Skills'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_work_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carer 2 Work Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='change_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Change Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_phone1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Phone.1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cpr_date',
            field=models.DateField(blank=True, null=True, verbose_name='CPR Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cub_investiture',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Cub Investiture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_left_scouting',
            field=models.DateField(blank=True, null=True, verbose_name='Date Left Scouting'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dietary_preferences',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dietary Preferences'),
        ),
        migrations.AlterField(
            model_name='member',
            name='disabilities',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Disabilities'),
        ),
        migrations.AlterField(
            model_name='member',
            name='doctors_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Doctor's Phone"),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_type',
            field=models.CharField(blank=True, choices=[('HTML', 'HTML'), ('Text', 'Text')], max_length=30, null=True, verbose_name='Email Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='member',
            name='employer_school',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Employer/School'),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='family_doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Family Doctor'),
        ),
        migrations.AlterField(
            model_name='member',
            name='family_notes',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Family notes'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_aid_cert',
            field=models.DateField(blank=True, null=True, verbose_name='First Aid Cert'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_invested',
            field=models.DateField(blank=True, null=True, verbose_name='First Invested'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_names',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Names'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='heard_about_scouts',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Heard about Scouts'),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Home Fax'),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_language',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Home Language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Home Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_file',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='member',
            name='interests',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='member',
            name='joey_investiture',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Joey Investiture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Review Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_tetanus_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Tetanus Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='main_email_address',
            field=models.EmailField(blank=True, help_text='Up to four emails can be added, separated by a semi-colon and no spaces. This is the only field that the system uses to send out emails.', max_length=254, null=True, verbose_name='Main Email Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_action_plan',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Medical Action Plan'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_conditions',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Medical conditions'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_fund',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Medical Fund'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medicare_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Medicare Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medications',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Medications'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('Adult Member', 'Adult Member'), ('Associate Leader', 'Associate Leader'), ('External Body', 'External Body'), ('Full Youth Member', 'Full Youth Member'), ('Non Member', 'Non Member'), ('Probationary Leader', 'Probationary Leader'), ('Second or Subsequent Child', 'Second or Subsequent Child'), ('Trainee Leader', 'Trainee Leader'), ('Woodbeaded Leader', 'Woodbeaded Leader')], max_length=30, null=True, verbose_name='Member Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Membership Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position_on_card',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Position on card'),
        ),
        migrations.AlterField(
            model_name='member',
            name='post_address_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Post Address 1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='post_address_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Post Address 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_postcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal Postcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal State'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_suburb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal Suburb'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pref_strength',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Pref. Strength'),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Preferred Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='qld_branch_family_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='QLD Branch Family Code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='quick_initials',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Quick Initials'),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='member',
            name='record_created',
            field=models.DateField(blank=True, null=True, verbose_name='Record Created'),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship_to_member',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Relationship to member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='member',
            name='residential_situation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Residential Situation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='rover_investiture',
            field=models.DateField(blank=True, null=True, verbose_name='Rover Investiture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='salutation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='scout_investiture',
            field=models.DateField(blank=True, null=True, verbose_name='Scout Investiture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='scout_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Scout Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='section',
            field=models.CharField(blank=True, choices=[('External Bodies', 'External Bodies'), ('Group', 'Group'), ('Joey', 'Joey'), ('Left', 'Left'), ('Monday Cub', 'Monday Cub'), ('Rover', 'Rover'), ('Scout', 'Scout'), ('Scouts Qld', 'Scouts Qld'), ('Venturer', 'Venturer'), ('Wednesday Cub', 'Wednesday Cub')], max_length=30, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sighted_blue_card',
            field=models.DateField(blank=True, null=True, verbose_name='Sighted Blue Card'),
        ),
        migrations.AlterField(
            model_name='member',
            name='six_patrol_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Six/Patrol/Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_media',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Social Media'),
        ),
        migrations.AlterField(
            model_name='member',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='member',
            name='suburb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Suburb'),
        ),
        migrations.AlterField(
            model_name='member',
            name='venturer_investiture',
            field=models.DateField(blank=True, null=True, verbose_name='Venturer Investiture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='waiting_list_comment',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Waiting list comment'),
        ),
        migrations.AlterField(
            model_name='member',
            name='waiting_list_date',
            field=models.DateField(blank=True, null=True, verbose_name='Waiting List Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='where_to',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Where to?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='work_fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Work Fax'),
        ),
        migrations.AlterField(
            model_name='member',
            name='work_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Work Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='yh_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='YH Appointment'),
        ),
    ]
