# Generated by Django 2.1.2 on 2019-03-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190130_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Family notes'),
        ),
    ]
