# Generated by Django 2.1.2 on 2019-03-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190313_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='post_address_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Address 1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='post_address_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Address 2'),
        ),
    ]
