# Generated by Django 2.1.2 on 2019-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190313_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_1_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carer 1 Occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='carer_2_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carer 2 Occupation'),
        ),
    ]
